### ISSUE TITLE
Add Python 3 support

### ISSUE THREAD

**Issue by dvejmz** [hotdoc/hotdoc_python_extension#1]
I tried running hotdoc with the Python extension installed against one of my Python 3 projects and the run failed with this error

```
Traceback (most recent call last):
  File "/usr/bin/hotdoc", line 30, in <module>
    doc_tool.setup(sys.argv[1:])
  File "/usr/lib/python2.7/site-packages/hotdoc/core/doc_tool.py", line 435, in setup
    extension.setup ()
  File "/usr/lib/python2.7/site-packages/hotdoc_python_extension/python_extension.py", line 253, in setup
    self.stale_source_files)
  File "/usr/lib/python2.7/site-packages/hotdoc_python_extension/python_extension.py", line 31, in __init__
    tree = ast.parse(code)
  File "/usr/lib/python2.7/ast.py", line 37, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 81
    def validate_heading_form(self) -> bool:
                                    ^
SyntaxError: invalid syntax
core setup done in 0:00:00.449729
extension c-extension done in 0:00:00.065918
extension gi-extension done in 0:00:00.000070
An unknown error happened while building the documentation and hotdoc cannot recover from it. Please report a bug with this error message and the steps to reproduce it
```

I'm pasting the error output for completeness but it's obvious the problem is that hotdoc's Python extension doesn't support Python 3 yet. Any plans to support it in the near future?

**Comment by MathieuDuponchelle** [comment]
Hm not yet , the module uses astroid to parse python code and we'll want to check how to use it on python3. Note that this module is written on a "scratch my own itch basis", and my sole purpose with it for the while is to have hotdoc document itself, for example for now only a specific format of docstring is supported ("google-style docstrings"). Patches welcome, otherwise I'll want to get to it at some point but it's not high priority :)

**Comment by MathieuDuponchelle** [comment]
So I've tried to google this issue real quick and afaict astroid can only parse python code for the major version of python that is used at runtime :/ That's a pretty bad limitation, and I think the way forward will be to use the [jedi](https://github.com/davidhalter/jedi) static analysis tools. Fortunately the extension is still very new, and there will not be that much code to port _wink_

**Comment by dvejmz** [comment]
Is that so? Oh well, I guess it can't be helped then. I'll have to work on this feature myself! Expect a pull request in a while :)

**Comment by MathieuDuponchelle** [comment]
Coool ! Seems like we'll both be working on projects we (want to) depend upon , way to go !

**Comment by MathieuDuponchelle** [comment]
Marking you as assignee to avoid potential duplication effort, it's mostly form as I don't think much people are yet interested in this extension but one never knows. If you are confused as to hotdoc's API, a _very WIP_ documentation can be found here -> https://people.collabora.com/~meh/hotdoc_hotdoc/html/python-extension-index.html , for all the undocumented symbols you can refer to other extensions.

You'll be the first person to work on a hotdoc's extension and the other is me, so feedback on this will of course be very helpful, if you want to discuss more directly I hang out in the #hotdoc channel on freenode.

**Comment by MathieuDuponchelle** [comment]
Hey, I pushed a simple jedi port as part of the `develop` branch. If you want to test it out with your python3 project I'd be grateful, it seemed to work with my very limited testing.

If you want to test that branch, you'll also need hotdoc's develop branch.

Otherwise I'll just merge this with the master branch as part of the 0.7 release very soon, and we'll see what comes out of it :)

**Comment by MathieuDuponchelle** [comment]
This was released, closing :)
